// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjxhdotwzffzobwfocpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qeGhkb3R3emZmem9id2ZvY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzU1NTQsImV4cCI6MjA1OTM1MTU1NH0.XOO1ZXVlOwRI_2NzMPb1_3RFsJgol2IFkLgjFOP8m6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);